version: "3"
services: 
  web:
    container_name: comment-tracker-node
    restart: always
    build: .
    ports: 
      - "5000:5000"
    links:
      - mongodb
    env_file: 
      - ./.env
  mongodb:
      container_name: mongodb
      image: mongo
      ports:
      - "27017:27017"